### ISSUE TITLE
Emacs loops/segfaults with certain buffer contents in certain major modes

### ISSUE THREAD

**Issue by nathanvy** [alphapapa/prism.el#18] opened 2023-05-12 05:28 UTC
Hi all,

edit:  Original title was "Prism mode causes emacs to freeze/lock up when typing double-quote characters on ARM macbooks"

Title says it all.  I am not sure how to debug this further, because emacs hangs entirely and the only way to recover is to force-quit the application.  I suppose one could use gdb or another debugger but I am not an expert in that sort of debugging and wouldn't know where to start.

Steps to reproduce:  
1. start emacs with blank config on M2 Macbook pro
2. Install Prism from MELPA (version "20230416.626" is what `package.el` pulled down for me)
3. 
```elisp
(use-package prism
    :commands prism-mode
    :init
    (add-hook 'prog-mode-hook #'prism-mode))
```
4. Open a `.lisp` file and attempt to type the following: `(#P"")` which is a Common Lisp pathname literal.  I have also seen this when editing HTML and attempting to type `<html lang="en">`

**Comment by alphapapa** [comment] 2023-05-13 01:42
Hi Nathan,

Thanks for reporting this.  I can confirm that there is a problem.  It's quite strange, and I'm surprised it took this long to be found.  Yet, it seems to only happen under certain circumstances, ones which I haven't encountered in my own usage, despite using `prism` every day.

Here's what I did to reproduce:

1.  Using https://github.com/alphapapa/with-emacs.sh: Run `with-emacs.sh -e emacs-28.2 -i prism`.
2. `C-x C-f /tmp/test.lisp RET`
3. `M-x prism-mode RET`
4. Type `(#P"")`.

After the first quotation mark (actually, after I press the key, but before it is displayed) Emacs goes into a 100%-CPU usage loop.  If I press `C-g`, Emacs will show the quotation mark and go into the loop again.  If I keep pressing `C-g`, I can get Emacs to respond to another keypress each time.  But as long as `prism-mode` is active in the buffer, Emacs will go into the loop trying to fontify that text.  (Another way to reproduce is to write that string into the buffer and then activate `prism-mode`.)

If, while Emacs is looping, I send the `SIGUSR2` signal, which should cause Emacs to quit and show a backtrace, instead Emacs segfaults:
```
Fatal error 11: Segmentation fault
Backtrace:
/home/me/.guix-profile/bin/emacs-28.2[0x529b7e]
/home/me/.guix-profile/bin/emacs-28.2[0x4257ca]
/home/me/.guix-profile/bin/emacs-28.2[0x425c62]
/home/me/.guix-profile/bin/emacs-28.2[0x528208]
/home/me/.guix-profile/bin/emacs-28.2[0x528279]
/gnu/store/5h2w4qi9hk1qzzgi1w83220ydslinr4s-glibc-2.33/lib/libpthread.so.0(+0x11d80)[0x7fac20ab1d80]
/home/me/.guix-profile/bin/emacs-28.2[0x4d6f9c]
/home/me/.guix-profile/bin/emacs-28.2[0x4d6fc3]
/home/me/.guix-profile/bin/emacs-28.2[0x4d6fc3]
/home/me/.guix-profile/bin/emacs-28.2[0x4d6fc3]
/home/me/.guix-profile/bin/emacs-28.2[0x4d6fc3]
/home/me/.guix-profile/bin/emacs-28.2[0x4d6fc3]
/home/me/.guix-profile/bin/emacs-28.2[0x4d6fc3]
/home/me/.guix-profile/bin/emacs-28.2[0x4d6fc3]
/home/me/.guix-profile/bin/emacs-28.2[0x4d6fc3]
/home/me/.guix-profile/bin/emacs-28.2[0x4d6fc3]
/home/me/.guix-profile/bin/emacs-28.2[0x4d6fc3]
/home/me/.guix-profile/bin/emacs-28.2[0x4d6fc3]
/home/me/.guix-profile/bin/emacs-28.2[0x4d6fc3]
/home/me/.guix-profile/bin/emacs-28.2[0x4d6fc3]
/home/me/.guix-profile/bin/emacs-28.2[0x4d6fc3]
/home/me/.guix-profile/bin/emacs-28.2[0x4d6fc3]
/home/me/.guix-profile/bin/emacs-28.2[0x4d6fc3]
/home/me/.guix-profile/bin/emacs-28.2[0x4d6fc3]
/home/me/.guix-profile/bin/emacs-28.2[0x4d6fc3]
/home/me/.guix-profile/bin/emacs-28.2[0x4d6fc3]
/home/me/.guix-profile/bin/emacs-28.2[0x4d6fc3]
/home/me/.guix-profile/bin/emacs-28.2[0x4d6fc3]
/home/me/.guix-profile/bin/emacs-28.2[0x4d6fc3]
/home/me/.guix-profile/bin/emacs-28.2[0x4d6fc3]
/home/me/.guix-profile/bin/emacs-28.2[0x4d6fc3]
/home/me/.guix-profile/bin/emacs-28.2[0x4d6fc3]
/home/me/.guix-profile/bin/emacs-28.2[0x4d6fc3]
/home/me/.guix-profile/bin/emacs-28.2[0x4d6fc3]
/home/me/.guix-profile/bin/emacs-28.2[0x4d6fc3]
/home/me/.guix-profile/bin/emacs-28.2[0x4d6fc3]
/home/me/.guix-profile/bin/emacs-28.2[0x4d6fc3]
/home/me/.guix-profile/bin/emacs-28.2[0x4d6fc3]
/home/me/.guix-profile/bin/emacs-28.2[0x4d6fc3]
/home/me/.guix-profile/bin/emacs-28.2[0x4d6fc3]
/home/me/.guix-profile/bin/emacs-28.2[0x4d6fc3]
...
/home/me/.bin/with-emacs: line 215: 130799 Segmentation fault      "$emacs" "${emacs_args[@]}"
```

I can confirm that the same thing happens in `html-mode` with the sample text you provided.  Note that `prism` is not intended for use with HTML (see https://github.com/alphapapa/prism.el/issues/16).  But, of course, Emacs should not freeze or crash with it activated.  However, `prism-whitespace-mode` does not cause a problem with that HTML fragment.

And, of course, typing the `(#P"")` text in `emacs-lisp-mode` (which is what I mostly use `prism-mode` for) causes no problems.

I tried using `font-lock-studio` to reveal the problem, but Emacs froze and crashed with it also.

So there may be a bug in Emacs here (because AFAIK Elisp should never be able to cause Emacs to segfault), but maybe also a bug in `prism` that's triggering it.  I'm guessing it's related to the syntax tables used by the major modes, since it happens in `lisp-mode` but not in `emacs-lisp-mode`.

And, of course, I'm not on an M2 Mac, so that appears to be unrelated to the problem.

For reference, what version of Emacs are you using, and where did the build come from?

As you said, I suppose one would need to use `gdb` to debug this.  I'm also not an expert with it, but I do recall that, if one makes an Emacs bug report, the developers will advise the reporter how to use `gdb` to get the necessary information.  Would you be willing to pursue that?  If not, I'll try to get to it eventually, but since I don't experience this problem myself, I probably won't have time to dig deeper anytime soon.

**Comment by nathanvy** [comment] 2023-05-13 07:06
> Hi Nathan,
> 
> Thanks for reporting this. I can confirm that there is a problem. It's quite strange, and I'm surprised it took this long to be found. Yet, it seems to only happen under certain circumstances, ones which I haven't encountered in my own usage, despite using `prism` every day.

You're most welcome, and thank you in return for Prism.

> I can confirm that the same thing happens in `html-mode` with the sample text you provided. Note that `prism` is not intended for use with HTML (see #16). But, of course, Emacs should not freeze or crash with it activated. However, `prism-whitespace-mode` does not cause a problem with that HTML fragment.

Thanks, I wasn't aware of `prism-whitespace-mode`!

> For reference, what version of Emacs are you using, and where did the build come from?

I've reproduced this on the [emacs-mac fork](https://bitbucket.org/mituharu/emacs-mac/src/master/) which is currently on 28.2, as well as the 28.2 build from [emacsformacosx.com](https://emacsformacosx.com/builds) which purports to be a straight port with minimal/no changes.

> As you said, I suppose one would need to use `gdb` to debug this. I'm also not an expert with it, but I do recall that, if one makes an Emacs bug report, the developers will advise the reporter how to use `gdb` to get the necessary information. Would you be willing to pursue that? If not, I'll try to get to it eventually, but since I don't experience this problem myself, I probably won't have time to dig deeper anytime soon.

Sure, I'll pursue that this week and report back here with any findings.

**Comment by alphapapa** [comment] 2023-05-14 04:08
Thank you!

**Comment by alphapapa** [comment] 2023-05-18 12:31
Hi Nathan,

I hope I have fixed it.  Please try this commit: https://github.com/alphapapa/prism.el/commit/ba531056e931c853cd9aafb7d91fb6193597a96d  It seems to work for me with the following test code in Elisp mode, and your test code in Lisp mode:
```el
(P"")
(P "")
(P P)
(P"foo bar")
(P "foo bar")
(P "foo")
(P """""")
```
Please test it and let me know if it works for you.  (Obviously, be sure to save any work in progress first, or use a separate Emacs session, in case it does still cause Emacs to crash.)

Thanks.

**Comment by nathanvy** [comment] 2023-05-18 22:09
Thanks for this. I'll take a look as soon as able, life's been very hectic lately so I haven't yet been able to put together an emacs bug report to upstream.

**Comment by alphapapa** [comment] 2023-05-19 06:22
Nevermind, I found that that change causes another bug.  I'll continue working on it.

**Comment by alphapapa** [comment] 2023-05-19 06:42
Ok, this commit seems to fix the problems noted here without causing any new problems: https://github.com/alphapapa/prism.el/commit/c438f91c454778d7234a4103d20b7e3ea0a12ee2  Please test it carefully and let me know what you find.  Thanks.

**Comment by alphapapa** [comment] 2023-05-19 10:10
It seems to be working well, so I merged it to master and released v0.3 with this fix.  @nathanvy Please do let me know how it works for you.  If there are any more problems, I'll release a fix in v0.3.1.

**Comment by nathanvy** [comment] 2023-05-19 15:56
Thanks again.  I noticed in your commit you mentioned prism isn't intended for HTML.  Should I be using `prism-whitespace-mode` instead for that?

**Comment by nathanvy** [comment] 2023-05-19 16:15
Okay thanks. I basically have been using prism for literally anything, haha.

**Comment by alphapapa** [comment] 2023-05-19 16:18
I'm glad whereever it works.  :)  As I described in #16, the Emacs functions for SGML-type languages aren't quite sufficient to do what `prism` is intended to do, but Emacs 29 will probably make that easier.

**Comment by alphapapa** [comment] 2023-05-19 16:19
@nathanvy BTW, did you confirm that this issue is fixed by v0.3?

**Comment by nathanvy** [comment] 2023-05-19 16:26
I've just tested now, while Peppa Pig was parenting my kids.  

This no longer freezes emacs:

```lisp
(#P"")
```

But this still does, immediately upon typing the doublequote.
```html
<html lang="
```

**Comment by alphapapa** [comment] 2023-05-19 17:15
@nathanvy Thanks for finding that.  I seem to have fixed it here: https://github.com/alphapapa/prism.el/commit/b1513e13cdcb918c0867866be4df475152e3c84c  Please let me know if that helps.  (It's the tip of the `wip/18` branch, which you can install with Straight.)

**Comment by nathanvy** [comment] 2023-05-19 17:38
Thanks I'll test it this evening

**Comment by nathanvy** [comment] 2023-05-21 07:26
> @nathanvy Thanks for finding that. I seem to have fixed it here: [b1513e1](https://github.com/alphapapa/prism.el/commit/b1513e13cdcb918c0867866be4df475152e3c84c) Please let me know if that helps. (It's the tip of the `wip/18` branch, which you can install with Straight.)

That change resolves the issue on my end, no longer able to reproduce!

**Comment by JasZhe** [comment] 2023-05-23 00:28
Hello I've also experienced this issue, I tried using the wip/18 branch but it still hangs here. I've was able to narrow it down to this minimum example to reproduce. 

``` go
// I'm a comment
foo = bar
```

The issue seems to be apostrophes in comments, I've disabled prism-comments for now as a workaround. Just FYI to anyone else stumbling across this

**Comment by fkr-0** [comment] 2023-05-23 14:35
```
[67181.425287] emacs[155037]: segfault at 560f914e5840 ip 00007f8abd68121a sp 00007ffdac05a7f0 error 7 in emacs-zmq.so[7f8abd600000+1a8000] likely on CPU 1 (core 0, socket 0)
[67181.425306] Code: 48 8b 03 48 8d 35 53 dd 0d 00 48 8b 68 10 48 89 c7 ff 50 58 48 8b 3b 48 89 c6 ff d5 48 8b 15 dd 2a 33 00 48 8d 35 db 53 0d 00 <48> 89 02 48 8b 03 48 8b 68 10 48 89 c7 ff 50 58 48 8b 3b 48 89 c6

```
just wanted to note that I also experienced this issue and can confirm that in my case
a) there were apostrophes in comments
b) turning off prism-comments works

**Comment by alphapapa** [comment] 2023-05-23 15:35
@JasZhe @fkr-0 I just pushed another commit to the WIP branch.  It seems to fix that problem.  Please test it and let me know if it does for you.  Thanks.

**Comment by alphapapa** [comment] 2023-05-23 15:48
I went ahead and pushed v0.3.1 that seems to fix this problem.  Please let me know your experience.  Thanks.

**Comment by polaris64** [comment] 2023-05-23 15:59
I was having this same issue this morning when trying to enable `prism-mode` in a buffer containing my Emacs init.el and this update has fixed it, thanks!

**Comment by alphapapa** [comment] 2023-05-23 17:38
@polaris64 Thanks for letting me know.

**Comment by sappigeninja** [comment] 2023-05-23 17:52
Just updated as well.
It stopped hanging :+1:.

**Comment by JasZhe** [comment] 2023-05-23 18:51
Updated to the latest master, re-enabled comments, it no longer freezes emacs, but I do get the infinite loop error message:

```
Error during redisplay: (jit-lock-function 1) signaled (error "prism: Infinite loop detected in ‘prism-match’ (buffer:#<buffer test_prism.go> point:5).  Please report this bug")
```

using the same example from before in `test_prism.go`:
```
// I'm a comment
foo = bar
```

Thank you for the quick turnaround on this!

**Comment by alphapapa** [comment] 2023-05-24 08:38
@JasZhe Hm, thanks, I'll look at that.

**Comment by JasZhe** [comment] 2023-05-24 21:56
🎉 working on my end now thanks! 

![image](https://github.com/alphapapa/prism.el/assets/15258281/333fc4b9-7507-47b0-908f-92ddeedf4db3)

**Comment by alphapapa** [comment] 2023-05-24 21:59
@JasZhe Great, thank you!

I didn't think many people were using `prism-comments`, but I'm glad to see it "in the wild."  :)

**Closed** 2023-05-24 22:04 UTC
Labels: bug, help wanted

**Comment by JasZhe** [comment] 2023-05-24 22:17
I'm a simple man, I just like seeing more pretty colors in my code :)

**Comment by alphapapa** [comment] 2023-05-24 22:19
We've gotta keep the fun in computing!

BTW, feel free to suggest any screenshots you think might look good in the readme: https://github.com/alphapapa/prism.el/issues/19  Your theme seems to fit prism well.
