### ISSUE TITLE
"End of buffer" message when running consult-line

### ISSUE THREAD

**Issue by meedstrom** [alphapapa/prism.el#9] opened 2021-08-10 17:50 UTC
I don't have the full steps to reproduce, because on emacs -Q it doesn't seem to happen, but for me when I have `(setq prism-comments nil)` and run the command `consult-line` in an elisp file, I get an "End of buffer" message and the prompt dies before it can start. It works after I re-run `consult-line` once or twice.

I've tried to use `toggle-debug-on-quit` and type C-g right after it happens, but Emacs doesn't seem to think there's anything to debug.

PS:  consult-line is similar to swiper or the old helm-swoop.

If you want more info let me know.

**Comment by alphapapa** [comment] 2021-08-10 18:11
This seems like a duplicate of #6.

**Comment by meedstrom** [comment] 2021-08-10 18:17
Shoot, I don't know how I missed that.

**Comment by alphapapa** [comment] 2021-08-10 18:26
:)  If you can help figure it out, that would be appreciated.  As I wrote there, it might be a simple change to Consult and/or Swiper to handle the error, but I don't know if it's necessarily a bug in those packages or in this one.

**Closed by alphapapa** 2021-08-10 18:26 UTC
